all: book01.out book02.out book03.out book04.out book05.out book06.out \
	 book07.out book08.out book09.out book10.out book11.out book12.out \
	 book13.out book14.out book15.out book16.out book17.out book18.out \
	 book19.out




book01.out:book01.cpp
	g++ book01.cpp -o book01.out -lpthread 

book02.out:book02.cpp
	g++ book02.cpp -o book02.out -lpthread 

book03.out:book03.cpp
	g++ book03.cpp -o book03.out -lpthread 

book04.out:book04.cpp
	g++ book04.cpp -o book04.out -lpthread 

book05.out:book05.cpp
	g++ book05.cpp -o book05.out -lpthread 

book06.out:book06.cpp
	g++ book06.cpp -o book06.out -lpthread 

book07.out:book07.cpp
	g++ book07.cpp -o book07.out -lpthread 

book08.out:book08.cpp
	g++ book08.cpp -o book08.out -lpthread 

book09.out:book09.cpp
	g++ book09.cpp -o book09.out -lpthread 

book10.out:book10.cpp
	g++ book10.cpp -o book10.out -lpthread 

book11.out:book11.cpp
	g++ book11.cpp -o book11.out -lpthread 

book12.out:book12.cpp
	g++ book12.cpp -o book12.out -lpthread 
	
book13.out:book13.cpp
	g++ book13.cpp -o book13.out -lpthread 

book14.out:book14.cpp
	g++ book14.cpp -o book14.out -lpthread 

book15.out:book15.cpp
	g++ book15.cpp -o book15.out -lpthread 

book16.out:book16.cpp
	g++ book16.cpp -o book16.out -lpthread 

book17.out:book17.cpp
	g++ book17.cpp -o book17.out -lpthread 

book18.out:book18.cpp
	g++ book18.cpp -o book18.out -lpthread 

book19.out:book19.cpp
	g++ book19.cpp -o book19.out -I/project/public /project/public/_public.cpp      -lpthread 





clean:
	rm book01.out book02.out book03.out book04.out book05.out book06.out book07.out book08.out
	rm book09.out book10.out book11.out book12.out book13.out book14.out book15.out book16.out
	rn book17.out book18.out book19.out